# Generated by Django 5.0.3 on 2024-04-19 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_notification_sender_alter_notification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='sender_name',
            field=models.CharField(default='', max_length=255, verbose_name='Имя отправителя'),
        ),
    ]
