# Generated by Django 5.0.3 on 2024-04-04 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_profile_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
